# This action runs on a local github runner
# See https://jano.dev/programming/2022/04/15/local-spm-ga.html

# To install xcpretty run:
# brew install ruby
# echo 'export PATH="/opt/homebrew/opt/ruby/bin:$PATH"' >> ~/.zshrc
# brew install xcpretty

name: Swift
on: [push]
jobs:
  ios-latest:
    name: Unit Tests (iOS 16.4, Xcode 14.3)
    runs-on: [self-hosted]
    env: 
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - name: Generate project
        run: |
          xcodegen
      - name: Build iOS
        run: |
          set -o pipefail && xcodebuild build -scheme "TumblrNPFPersistence" -destination "OS=16.4,name=iPhone 14 Pro" -skipPackagePluginValidation | xcbeautify
      - name: Build Mac
        run: |
          set -o pipefail && xcodebuild build -scheme "TumblrNPFPersistence" -destination "platform=macOS,arch=arm64" -skipPackagePluginValidation | xcbeautify
